# -*- coding: utf-8 -*-
"""MangaOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l0O_-GAv-RyTprDnStqh2cVR-c_NkcLz
"""

import os
path = "/content"
os.chdir(path)

!pip3 install manga-ocr
!mkdir data

from google.colab import files

path = "/content/data"
os.chdir(path)
image = files.upload()
image_name = list(image.keys())[0]

import PIL.Image
from manga_ocr import MangaOcr

mocr = MangaOcr()
img = PIL.Image.open(image_name)
text = mocr(img)
print(text)

!rm -rf /content/data/